# Generated by Django 4.2.4 on 2023-12-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathsPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadratics', models.IntegerField(blank=True, default=0)),
                ('equations_and_inequalities', models.IntegerField(blank=True, default=0)),
                ('graphs_and_transformations', models.IntegerField(blank=True, default=0)),
                ('straight_line_graphs', models.IntegerField(blank=True, default=0)),
                ('circles', models.IntegerField(blank=True, default=0)),
                ('trigonometry', models.IntegerField(blank=True, default=0)),
                ('differentiation', models.IntegerField(blank=True, default=0)),
                ('integration', models.IntegerField(blank=True, default=0)),
                ('two_d_vectors', models.IntegerField(blank=True, default=0)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.studentuser')),
            ],
        ),
        migrations.CreateModel(
            name='FurtherMathsPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('differentiation', models.IntegerField(blank=True, default=0)),
                ('integration', models.IntegerField(blank=True, default=0)),
                ('argand_diagrams', models.IntegerField(blank=True, default=0)),
                ('volumes_of_revolution', models.IntegerField(blank=True, default=0)),
                ('methods_in_calculus', models.IntegerField(blank=True, default=0)),
                ('matrices', models.IntegerField(blank=True, default=0)),
                ('polar_coordinates', models.IntegerField(blank=True, default=0)),
                ('hyperbolic_functions', models.IntegerField(blank=True, default=0)),
                ('three_d_vectors', models.IntegerField(blank=True, default=0)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.studentuser')),
            ],
        ),
    ]
