# Generated by Django 4.2.4 on 2024-01-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_question_answer_box_question_is_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='questions/default.jpg', null=True, upload_to='questions/'),
        ),
    ]
