# Generated by Django 4.2.4 on 2024-03-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_mathspoints_three_d_vectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_board',
            field=models.CharField(blank=True, choices=[('AQA', 'AQA'), ('Edexcel', 'Edexcel'), ('OCR', 'OCR'), ('WJEC', 'WJEC')], max_length=30, null=True),
        ),
    ]
