# Generated by Django 4.2.4 on 2024-04-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_question_exam_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathspoints',
            name='parametrics',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, choices=[('Quadratics', 'Quadratics'), ('Equations and Inequalities', 'Equations and Inequalities'), ('Graphs and Transformations', 'Graphs and Transformations'), ('Straight Line Graphs', 'Straight Line Graphs'), ('Circles', 'Circles'), ('Trigonometry', 'Trigonometry'), ('Parametric Equations', 'Parametric Equations'), ('Differentiation', 'Differentiation'), ('Integration', 'Integration'), ('Exponentials and Logarithms', 'Exponentials and Logarithms'), ('2D Vectors', '2D Vectors'), ('Argand Diagrams', 'Argand Diagrams'), ('Volumes of Revolution', 'Volumes of Revolution'), ('Methods In Calculus', 'Methods In Calculus'), ('Matrices', 'Matrices'), ('3D Vectors', '3D Vectors'), ('Polar Coordinates', 'Polar Coordinates'), ('Hyperbolic Functions', 'Hyperbolic Functions')], max_length=100, null=True),
        ),
    ]
